// <auto-generated />
using System;
using EF_CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CodeFirst.Migrations
{
    [DbContext(typeof(EfCodeFirstContext))]
    partial class EfCodeFirstContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            GradeName = "5",
                            Section = "Matematika",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 2,
                            GradeName = "4",
                            Section = "Hrvatski jezik",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 3,
                            GradeName = "5",
                            Section = "Priroda i društvo",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 4,
                            GradeName = "3",
                            Section = "Engleski jezik",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 5,
                            GradeName = "4",
                            Section = "Matematika",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 6,
                            GradeName = "5",
                            Section = "Likovna kultura",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 7,
                            GradeName = "4",
                            Section = "Tjelesna i zdravstvena kultura",
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DateOfBirth = new DateTime(2012, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 135.2m,
                            StudentName = "Ana Marić",
                            Weight = 32.5
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateTime(2011, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 140.7m,
                            StudentName = "Ivan Novak",
                            Weight = 36.0
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.HasOne("EF_CodeFirst.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
